-- Script para inserir os Funcionários (Garante unicidade pelo nome)
-- Primeiro, garante que o nome seja único para o comando INSERT funcionar corretamente
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'people_name_key') THEN
        ALTER TABLE public.people ADD CONSTRAINT people_name_key UNIQUE (name);
    END IF;
END $$;

INSERT INTO public.people (name, is_registered) VALUES
('Alexandre Augusto Teixeira', true),
('Alexandre Pereira de Lima', true),
('Anderson Gomes Nunes', true),
('Andre dos Reis Santos', true),
('Antonio Paulo Teixeira', true),
('Brenno Mendes de Sousa', true),
('Bruno Alves de Moraes Sarmento Duarte', true),
('Carla Chimera Nardim', true),
('Carlos Alberto da Silva', true),
('Cicero Manoel da Silva', true),
('Dannilo Richerdson C Queiroz', true),
('Davi Magistrali Rocco', true),
('Debora dos Santos Aragao', true),
('Debora Vitoria Oliveira Bezerra', true),
('Denesio Cardoso', true),
('Diego Evandro Maria Martins', true),
('Edigenaldo Leal da Costa', true),
('Eduardo Cardoso Garcia', true),
('Edwin de Carvalho Pereira', true),
('Elias dos Santos Aragao', true),
('Evandro Luiz de Moraes', true),
('Everton Simões Fernandes Teixeira', true),
('Franciluvio Gomes da Silva', true),
('Gabriel Marques Vieira', true),
('Guilherme Florencio Lisboa', true),
('Italo Elmer Lima', true),
('Italo Guitar de Santana dos Santos', true),
('Janivaldo Roberto de Luna', true),
('Jessica de Souza Franco', true),
('Joao Luiz Madureira', true),
('Jose dos Santos Xavier', true),
('Jose Jonas Carvalho Silva', true),
('Jose Luiz Marin', true),
('Jozilda Nunes de Oliveira', true),
('Juliane Silva dos Anjos', true),
('Keisy Minene Pereira Marques Baciga', true),
('Leonardo Guilherme de Souza', true),
('Leonardo Roberto Pereira da Silva', true),
('Leticia Oliveira da Silva', true),
('Leudimar Maria Costa Andrade', true),
('Lucas Santos de Araujo', true),
('Luciene da Silva Santos', true),
('Luiz Gustavo Silva', true),
('Maiara de Souza da Silva Dias', true),
('Marcio Oliveira dos Santos', true),
('Marcus Vinicius da Silva Lima', true),
('Mauro Sergio Dalbem', true),
('Menandro Rodrigues Filgueira', true),
('Michele Ferreira dos Santos', true),
('Monique Godoy da Silva Andrade', true),
('Nanci do Nascimento Ferreira Luis', true),
('Odair Jose Tomaz', true),
('Paulo dos Santos Xavier', true),
('Paulo Henrique Soares', true),
('Rafael Ferreira da Silva', true),
('Raphael Teixeira dos Santos', true),
('Raquel Aparecida da Silva', true),
('Rodrigo Estevao de Lima', true),
('Samuel Magalhaes', true),
('Tamires Alves dos Santos', true),
('Taynan Modesto Rodrigues da Silva', true),
('Tomas Di Febbo', true),
('Victor Henrique Tecco', true),
('Vinicius Franco de Souza', true),
('Wanderson Reis Souza', true),
('Yasmin de Souza Andrade', true),
('Adam de Pierre Pavan', false),
('Ademilson Souza de Jesus', false),
('Adilson Felix de Oliveira', false),
('Adolfo Belchior de Sousa', false),
('Adriano Mariano', false),
('Adson Silva Costa', false),
('Aecio Vieira Zimerer', false),
('Agenilson Bernardo da Silva', false),
('Agenor Silva de Almeida', false),
('Airton Souza de Jesus', false),
('Alan Lima dos Anjos', false),
('Alan Soares Machado', false),
('Alecsandro de Paula dos Anjos', false),
('Alex Jesus Gomes', false),
('Alex Martiliano da Silva', false),
('Alexandre Augusto Lacerda', false),
('Alexandre Batista Freitas da Silva ', false),
('Alexandre da Silva', false),
('Alexrandre Porfirio dos Santos', false),
('Alexandre Ricardo dos Santos ', false),
('Alexandro Antunes de Sousa', false),
('Aline Brito Levi da Silva', false),
('Allan Bruno Ribeiro de Lima', false),
('Ana Paula de Jesus Santos', false),
('Ana Rogeria da Silva', false),
('Ana Sabrina dos Santos Xavier', false),
('Anderson de Jesus Silva', false),
('Anderson Pinheiro de Sá', false),
('Anderson Ramos Cardoso', false),
('Anderson Viana Medeiros', false),
('André Duarte dos Santos ', false),
('Andreia Franco', false),
('Andrey Buscarani dos Santos Silva', false),
('Angelica Ferreira Magalhães', false),
('Anny Vitoria da Silva Rodrigues', false),
('Antonio Calixto de Sousa ', false),
('Antonio Carlos Bezerra dos Santos', false),
('Antonio Felipe Alves Ramos', false),
('Antonio Francisco Gomes de Oliveira', false),
('Antonio Marcos do Nascimento', false),
('Antonio Rivaldo Gomes Bezerra', false),
('Antonio Roberto Santos de Oliveira', false),
('Ashiley Ney Pereira Ribeiro de Oliveira', false),
('Beatriz Cezar Valerio de Jesus', false),
('Bruno Almeida da Silva', false),
('Bruno de Lima Silva', false),
('Bruno Inacio Alves Silva ', false),
('Bruno Leandro França Marvino', false),
('Bruno Luiz de Souza Franzin', false),
('Bruno Vilas Boas de Oliveira', false),
('Bruno Yoshiharu Sakosigue Correa', false),
('Carlos Alberto Silva Ramilo', false),
('Carlos Alberto Beserra Goes', false),
('Carlos Eduardo Pereira Silva ', false),
('Carlos Farias dos Santos', false),
('Carlos Henrique Dias da Cruz', false),
('Carlos Alberto dos Santos Junior ', false),
('Carlos Rafael Dias da Cruz', false),
('Carlos Rafael Dias da Cruz ', false),
('Cassiano Cabral da Silva', false),
('Cassio Breno Faustino do Nascimento', false),
('Cicero Bezerra da Cunha', false),
('João Cicero Martins da Silva', false),
('Cicero Romão Santos de Souza', false),
('Cintia Priscila dos Santos', false),
('Claudinei Cherchiglia', false),
('Claudio Roberto da Silva ', false),
('Clayton de Paula dos Anjos ', false),
('Cleber de Melo Simões', false),
('Cleiton Cavasso de lima', false),
('Cleiton do Carmo de Novais', false),
('Cristiano Chiarella Ortiz', false),
('Cristiano de Albuquerque', false),
('Cristiano de Jesus Ferreira', false),
('Critiano de Jesus Ferreira', false),
('Cristiano de Oliveira', false),
('Cristiano Francisco de Oliveira', false),
('Cristiano Oliveira', false),
('Cristiano Trujilho', false),
('Daniel Bartolo Felix', false),
('Daniel da Silva Bezerra', false),
('Daniel Matias da Costa', false),
('Daniela Maria Teixeira ', false),
('Danilo dos Santos Mattos', false),
('Danilo Santos Poloni', false),
('Davi Aragão Andrade Pereira ', false),
('Davi Oliveira de Souza', false),
('David Ferreira Alves', false),
('Deborah Aragao Verissimo Ramalho', false),
('Denis Aparecido Rosa Santana', false),
('Denis Danilo da Silva Bezerra', false),
('Denis Araujo Justos', false),
('Denison de Freitas Francisco Sales', false),
('Dennis de Oliveira Farkas', false),
('Deyvson Gomes da Silva', false),
('Diego da Conceição', false),
('Diego Ferreira Lopes', false),
('Diego Moreira Dias', false),
('Diemerson Jesus da Conceição', false),
('Diogo da Cuz Batista ', false),
('Donald Pereira Rodrigues', false),
('Donizete Luiz dos Santos', false),
('Douglas da Silva', false),
('Douglas de Moraes', false),
('Edersom Mendes dos Santos', false),
('Edilson Jose de Arruda', false),
('Edmilson Jose da Silva', false),
('Edinaldo da Silva', false),
('Edmar Nunes Bento ', false),
('Edmilson de Queiroz Brandão', false),
('Edson Luiz Rodrigues da Silva Junior', false),
('Edson Viana Homena', false),
('Eduardo Araujo Mesquita', false),
('Eduardo Melillo', false),
('Eduardo Rodrigues Ferraz', false),
('Eduardo Tadeu Amador', false),
('Edvaldo Gomes da Silva ', false),
('Edvan Gonçalves Dantas', false),
('Eliezer Silva Santos Oliveira', false),
('Eloisio Marques de Oliveira', false),
('Elton Luis Salles de Carvalho', false),
('Emerson Nunes de Santana', false),
('Emilena dos Santos Aragão', false),
('Erick Pereira Santana', false),
('Erivaldo Lopes Oliveira', false),
('Esteffani Xavier Nunes', false),
('Estevão Martiliano da Silva', false),
('Eugenio Paulino Oliveira de Barros', false),
('Evaldo Correia da Silva', false),
('Evelyn Cristiny Reis da Silva', false),
('Everton Lima Tavares', false),
('Fabiano Moreira Santos', false),
('Fabio Candido da Silva', false),
('Fabio Miguel dos Santos', false),
('Fabio Rogerio Marques', false),
('Fabio Sinisgalli Machado', false),
('Fabricio Aparecido Fernandes dos Santos', false),
('Fabricio Saraiva Duarte', false),
('Felipe Araujo Ramilo', false),
('Felipe Augusto da Silva', false),
('Felipe Marques Fedelis de Souza ', false),
('Felipe Soares Leonel ', false),
('Felipe de Souza Vieira', false),
('Felipe Wesley de Santana', false),
('Felipe Weygner Lopes da Silva', false),
('Fernanda Silva Azevedo', false),
('Fernando da Costa Martins', false),
('Fernando dos Santos Soldi', false),
('Fernando Gonçalves de Melo Filho', false),
('Flavio Dias de Andrade', false),
('Flavio Freire de Queiroz Costa', false),
('Francisco Cleio Gomes de Souza', false),
('Francisco Helio da Silva Gomes', false),
('Francisco Jose Gomes Mendes', false),
('Francisco Luan Fernandes Duarte', false),
('Francisco Ronaldo Vericio Junior', false),
('Francisco Segundo de Oliveira Mariz', false),
('Gabriel Augusto Nunes', false),
('Gabriel Barros Lima', false),
('Gabriel Bispo', false),
('Gabriel Costa da Silva', false),
('Gabriel Dias da Silva ', false),
('Gabriel Franco de Souza', false),
('Gabriel Vieira Souza Santos', false),
('Gabriela Alves da Silva', false),
('Gabriela Aragão Ferreira', false),
('Gabrielle Aparecida Ferreira Tomaz', false),
('Genilson do Carmo de Novais', false),
('Geovane José da Silva ', false),
('Geovanna Luiza Silva Chagas', false),
('Gerson Ricardo de Souza Oliveira Alves', false),
('Glayson Alves Souza', false),
('Gleison Barreto da Fonseca', false),
('Gustavo de oliveira', false),
('Gustavo Felipe de Oliveira', false),
('Gustavo Inacio Pares', false),
('Gustavo Santos Policarpo Silva', false),
('Gustavo Silva Soares', false),
('Gustavo Yan da Rocha Almeida', false),
('Hector Gabriel Milano Hernandes', false),
('Heitor Paduam ', false),
('Helvecio da Silva', false),
('Henrique Barbosa Alves', false),
('Herick Araujo de Souza', false),
('Humberto Biagi Mminer', false),
('Humberto Henrique Ferreira Bueno da Silva', false),
('Iago Amaral', false),
('Iago Kauan Bernegosso', false),
('Igor e Silva dos Santos', false),
('Igor Matheus Nunes de Almeida', false),
('Ingrid Bezerra Mendes e Silva', false),
('Isaquiel Santos de Lima', false),
('Ismael Barbosa da Silva', false),
('Jackson Jose da Silva', false),
('Jackson Muller dos Santos ', false),
('Jailson Alonso de Souza', false),
('Janaina Santos Silva', false),
('Jaqueline Kilma Silva Lins', false),
('Jaquison Limeira Santos', false),
('Jasiel da Silva Bezerra', false),
('Jean Carlo Honorio da Silva Junior', false),
('Jefferson dos Santos Barbosa', false),
('Jefferson Gomes dos Santos', false),
('Jesualdo Pereira da Lima Teles', false),
('Jesus Sebastian', false),
('Jhonatan Carlos Candido', false),
('Jhonatas Rocha Bernardes da Silva', false),
('Jhonathan Italo Fernandes Veide', false),
('João Carlos Pinheiro', false),
('João Carlos Silva de Araujo', false),
('João Cícero Martins da Silva ', false),
('Joao Gabriel Pereira Barbosa', false),
('Joao Victor Mendes de Sousa', false),
('João Vitor Duarte de Sousa', false),
('Jobanny Jose Urbano Aleman', false),
('Joel Neves da Conceicao Filho', false),
('John Diego Benites da Silva', false),
('Johny Cesar de Brito Tavares', false),
('Jonata Arrais do Nascimento', false),
('Jonata de Sousa Alexandre', false),
('Jose Augusto Silva Ferreira ', false),
('Jose Carlos Cavalcante', false),
('Jose Correia de Aarujo Neto', false),
('Jose da Silva Araujo', false),
('Jose Edson Paduan', false),
('Jose Everton de Jesus', false),
('Jose Francisco Barros da Silva', false),
('José Gabriel Reis Rodrigues', false),
('Jose Gomes dos Santos', false),
('Jose Ilton da Silva Santos', false),
('Jose Patricio Calixto dos Santos ', false),
('jose Raimundo dos Santos Ferreira', false),
('Joseph Pereira Bultcher', false),
('Josilene Sousa de Araujo', false),
('Josimar Ferreira de Franca', false),
('Josimar Santos Marambaia', false),
('Josinaldo Gonzaga de Melo', false),
('Jozilda Nunes de Oliveira', false),
('Julia de Paula Ferreira', false),
('Julio Cesar Soares de Souza', false),
('Julio Cesar Pinheiro Carneiro', false),
('Kairon Aguiar da Silva', false),
('Karine Alves Silva', false),
('Kauan Ribeiro da Silva', false),
('Laercio Jose de Souza', false),
('Larissa Rodrigues Costa Araujo', false),
('Leandro Alves', false),
('Leandro Aparecido dos Anjos ', false),
('Leandro Coelho', false),
('Leandro Oliveira Ferreira', false),
('Leandro Pereira', false),
('Leandro Rodrigues de Morais', false),
('Leonardo da SIlva Pereira', false),
('Marcos Fernandes', false),
('Leonardo Frank Devis Avila', false),
('Luan Leonardo dos Santos ', false),
('Luana Aparecida de Almeida Silva', false),
('Luana de Jesus dos Santos ', false),
('Lucas Almeida', false),
('Lucas Alves Pereira Costa', false),
('Lucas Caetano dos Santos e Silva', false),
('Lucas Eduardo de Araujo', false),
('Lucas de Oliveira Messias', false),
('Luciano Andrioni da Costa', false),
('Luciano Firmino da Silva', false),
('Luciano Silva dos Santos', false),
('Luis Antonio Guimaraes', false),
('Luis Fernando Batista Soares', false),
('Luiz Antonio Guimarães de Almenida ', false),
('Luiz Eduardo Bezerra Silva', false),
('Luiz Felipe Silva Francisco', false),
('Luiz Felipe da Silva', false),
('Luiz Fernando de Oliveira', false),
('Luiz Fernando Paduan de Lima', false),
('Luiz Gustavo dos Santos de Oliveira', false),
('Luiz Gustavo do Rosario de Almeida Vaz', false),
('Luiz Henrique de Jesus Nascimento', false),
('Luiz Pereira Batista da Silva ', false),
('Maciel Magalhães Nascimento', false),
('Maele Brito Goes Gomes', false),
('Magno Muniz da Silva', false),
('Maiko de oliveira Silva', false),
('Miakon Guilherme Matos Bonfim', false),
('Mailson Amorim Soares ', false),
('Marcelo de Oliveira', false),
('Marcelo de Souza', false),
('Marcelo Fausto da Silva', false),
('Marcelo Nascimento de Souza', false),
('Marcelo Ramos de Jesus', false),
('Marcio Araujo dos Passos ', false),
('Marcos Antonio de Jesus', false),
('Marcos Antonio de Amorim ', false),
('Marcos Antunes Pereira', false),
('Marcos Candido da Silva', false),
('Marcos Cesar Silva do Nacimento', false),
('Marcos Gonçalves dos Santos Ferreira', false),
('Marcos Henrique Marim Pannia', false),
('Marcos Kaique Iafrate da Silva', false),
('Marcos Vinicius Emiliano Alves', false),
('Marcus Paulo Oliveira Viana', false),
('Maria Lucimar Luima Ferreira', false),
('Maria Natalia da Conceicao Silva', false),
('Mariana Basilio Vieira Fernandes Matos', false),
('Mariana Batista Pereira', false),
('Mariana do Nascimento Lopes dos Santos ', false),
('Mariane Bispo Roseno', false),
('Mario Alves de Santana', false),
('Mario Eduardo Garcia Benitez', false),
('Marlon Nobrega Pfister', false),
('Marlon Pereira Silva', false),
('Marlon Silva Santana', false),
('Mateus Barbosa Rodrigues da Silva', false),
('Mateus Martins de Carvalho Licar', false),
('Mateus da Silva de Almeida', false),
('Mateus Martins da Costa ', false),
('Matheus Alves dos Santos', false),
('Matheus Aparecido Silva de Araujo', false),
('Matheus Duarte de Sousa', false),
('Matheus Goncalves', false),
('Matheus Vieira dos Santos', false),
('Mauricio da Silva', false),
('Mauricio de Moura', false),
('Mauricio Gomes Silva', false),
('Mauro Jose Ferreira ', false),
('Maykon Nunes Cruz', false),
('Maykon Silva Santos ', false),
('Messias Fernandes da Silva', false),
('Murilo da Silva Claudino', false),
('Muryllo Conceição da Silva', false),
('Nataline Gomes de Araujo', false),
('Natan Evangelista de Souza', false),
('Nayara Lourenço da Silva Santos', false),
('Nicolas Pedroza Campeiro Vaz', false),
('Nicolas Silva dos Santos', false),
('Odair Evaristo ramoni Junior', false),
('Osano Dantas Sá ', false),
('Oscar Gustavo Garcia Perez', false),
('Oscar Gustavo Garcia Perez Junior', false),
('Otavio Henrique Carvalho dos Santos ', false),
('Pablo Cesar Garcia Benitez', false),
('Paloma Nascimento Dias', false),
('Pasquale Marco Marrone', false),
('Paula da Silva Barbosa', false),
('Paulo Djonhes Ribeiro da Silva', false),
('Paulo Marcelo Duarte Brito', false),
('Paulo Sergio Barbosa Elias', false),
('Paulo Sergio da Silva', false),
('Paulo Sergio Pereira da Silva', false),
('Paulo Victor Gomes da Silva', false),
('Pedro Henrique da Silva Souza', false),
('Pedro Tabolassi da Silva', false),
('Rafael da Silva Tonini', false),
('Rafael da Silva Nunes de Jesus', false),
('Rafael Peroco', false),
('Rafael Warzee dos Santos', false),
('Raphael Abreu Magalhaes', false),
('Reinaldo Almeida Prudente', false),
('Reinaldo Braga Tavares', false),
('Renan Vieira Martins de Gregorio', false),
('Renata Figueredo Rodrigues', false),
('Renato de Aquino Ribeiro', false),
('Renato Sena dos Santos junior', false),
('Renato Sousa da Silva', false),
('Ricardo Alexandre Miguel', false),
('Ricardo Nascimento Portela', false),
('Ricardo Prado  Magalhães', false),
('Roberto Anderson Moura', false),
('Roberto Jose Sarmiento Carrillo', false),
('Roberto Leandro Martins Pereira', false),
('Robertson dos Santos Rocha', false),
('Robson Carlos Santos', false),
('Robson Lopes da Silva', false),
('Robson Mendes Oliveira Morais', false),
('Rocelio Francisco de Melo', false),
('Rochenildo Jose da Silva', false),
('Rodolfo da Silva Nunes', false),
('Rodrigo Alex Tavares Ignacio', false),
('Rodrigo Alves', false),
('Rodrigo de Jesus Gonçalves de Souza ', false),
('Rodrigo Nascimento de Souza ', false),
('Rogerio Henrique Martins da Cunha', false),
('Romulo Benedito Cavalcante Teixeira', false),
('Ronaldo Aparecido de Souza', false),
('Roosevelt Nery de Campos', false),
('Sandra Regina Varano', false),
('Sandro Mendes Silva', false),
('Sergio Alejandro Facchinett Maluf', false),
('Sergio Oliveira Santos ', false),
('Siloel Antonio do Nascimento', false),
('Simone Ferreira Bueno', false),
('Stefany Silva Soares', false),
('Sthefany Barbosa Queiroz', false),
('Talyson Lourenco Oliveira da Silva', false),
('Thamiris dos Santos Diniz', false),
('Thaynara Christine Araujo Pereira', false),
('Thayrone Lima D Assumpção', false),
('Thiago Gabriel da Silva', false),
('Thiago Henrique Varano Evangelista', false),
('Thiago Mantovani de Oliveira Ramos', false),
('Thiago da Silva Monteiro', false),
('Thiago Teixeira da Silva', false),
('Tiago Rocha da Silva', false),
('Tiago Ribeiro dos Santos', false),
('Tony Kifua Lin', false),
('Valdson Vagno Silva dos Santos', false),
('Vandemarcos Marques da Silva', false),
('Vanderlei Batista Pereira', false),
('Victor Lino da Silva', false),
('Victor Silvestre da Silva', false),
('Victorio Augusto Duarte de Sousa', false),
('Vinicius dos Santos Chaves', false),
('Vinicius Gabriel Ferreira de Souza', false),
('Vitor Nunes Silva', false),
('Vitoria Nascimento Dias', false),
('Wagner Rodrigues Cacimiro', false),
('Wanderson Reis Souza', false),
('Welker de Jesus Paim', false),
('Wellington Carlos de Souza Evangelista ', false),
('Wellington Vieira de Souza', false),
('Welton dos Santos Fonseca', false),
('Weslei Vicente Ferreira Fernandes de Souza', false),
('Weslwy Gonçalves Guedes', false),
('Weslley Gonçalves dos Santos', false),
('Weverton Vitor Oliveira da Cruz', false),
('Wilkerson Alves dos Santos Costa', false),
('Willian Honorio Pereira de Sousa', false),
('Wladimir Antonio Garcia', false),
('Yuri Henrique Soares de Souza', false),
('Fabio Paulino dos Santos', false)
ON CONFLICT (name) DO NOTHING;

-- POLÍTICAS DE ACESSO (RODE ISSO PARA GARANTIR QUE APAREÇAM NO APP)
ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for people" ON public.people;
CREATE POLICY "Enable all for people" ON public.people FOR ALL USING (true) WITH CHECK (true);
